name: Run checks and tests
on:
  workflow_dispatch:
  push:
    branches: [ main, develop, feature/gh-actions ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        run: cargo fetch

      - name: Check
        run: cargo check --all-features

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run : cargo test --all-features